// Generated by scripts/build.mjs – do not edit. Run `npm run build` after adding icons.
window.ICONS = [
 {
  "name": "arrow-down",
  "category": "arrows",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M12 5v14M6 13l6 6 6-6\"/>",
  "mode": "stroke"
 },
 {
  "name": "arrow-left",
  "category": "arrows",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M19 12H5M11 6l-6 6 6 6\"/>",
  "mode": "stroke"
 },
 {
  "name": "arrow-right",
  "category": "arrows",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M5 12h14M13 6l6 6-6 6\"/>",
  "mode": "stroke"
 },
 {
  "name": "arrow-up-right",
  "category": "arrows",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M7 17 17 7M8 7h9v9\"/>",
  "mode": "stroke"
 },
 {
  "name": "arrow-up",
  "category": "arrows",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M12 19V5M6 11l6-6 6 6\"/>",
  "mode": "stroke"
 },
 {
  "name": "chevron-down",
  "category": "arrows",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"m6 9 6 6 6-6\"/>",
  "mode": "stroke"
 },
 {
  "name": "chevron-left",
  "category": "arrows",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"m15 6-6 6 6 6\"/>",
  "mode": "stroke"
 },
 {
  "name": "chevron-right",
  "category": "arrows",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"m9 6 6 6-6 6\"/>",
  "mode": "stroke"
 },
 {
  "name": "chevron-up",
  "category": "arrows",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"m6 15 6-6 6 6\"/>",
  "mode": "stroke"
 },
 {
  "name": "swap",
  "category": "arrows",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M4 8h15M15 4l4 4-4 4M20 16H5M9 12l-4 4 4 4\"/>",
  "mode": "stroke"
 },
 {
  "name": "trending-down",
  "category": "arrows",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"m3 7 6 6 4-4 8 8M15 17h6v-6\"/>",
  "mode": "stroke"
 },
 {
  "name": "trending-up",
  "category": "arrows",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"m3 17 6-6 4 4 8-8M15 7h6v6\"/>",
  "mode": "stroke"
 },
 {
  "name": "award",
  "category": "commerce",
  "tags": [
   "badge",
   "medal",
   "prize"
  ],
  "viewBox": "0 0 24 24",
  "body": "<circle cx=\"12\" cy=\"9\" r=\"6\"/><path d=\"m8.5 14-1.5 7 5-3 5 3-1.5-7\"/>",
  "mode": "stroke"
 },
 {
  "name": "bag",
  "category": "commerce",
  "tags": [
   "shopping",
   "store"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M5 8h14l-1 13H6z\"/><path d=\"M9 10V7a3 3 0 0 1 6 0v3\"/>",
  "mode": "stroke"
 },
 {
  "name": "briefcase",
  "category": "commerce",
  "tags": [
   "work",
   "job",
   "business"
  ],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"3\" y=\"7\" width=\"18\" height=\"13\" rx=\"2\"/><path d=\"M9 7V5a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2M3 13h18\"/>",
  "mode": "stroke"
 },
 {
  "name": "cart",
  "category": "commerce",
  "tags": [
   "shopping",
   "basket",
   "buy"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M3 4h2l2.5 11h11L21 7H6.5\"/><circle cx=\"9\" cy=\"19.5\" r=\"1.5\"/><circle cx=\"17\" cy=\"19.5\" r=\"1.5\"/>",
  "mode": "stroke"
 },
 {
  "name": "chart-bar",
  "category": "commerce",
  "tags": [
   "analytics",
   "stats",
   "graph"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M4 20h16M7 16v-5M12 16V6M17 16V8\"/>",
  "mode": "stroke"
 },
 {
  "name": "chart-line",
  "category": "commerce",
  "tags": [
   "analytics",
   "stats",
   "graph"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M4 4v16h16\"/><path d=\"m7 14 4-4 3 3 5-6\"/>",
  "mode": "stroke"
 },
 {
  "name": "chart-pie",
  "category": "commerce",
  "tags": [
   "analytics",
   "stats"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M12 3a9 9 0 1 0 9 9h-9z\"/><path d=\"M15 3.5A9 9 0 0 1 20.5 9H15z\"/>",
  "mode": "stroke"
 },
 {
  "name": "credit-card",
  "category": "commerce",
  "tags": [
   "payment",
   "card",
   "money"
  ],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"3\" y=\"5\" width=\"18\" height=\"14\" rx=\"2\"/><path d=\"M3 10h18M7 15h3\"/>",
  "mode": "stroke"
 },
 {
  "name": "flag",
  "category": "commerce",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M5 21V4M5 4h11l-2 4 2 4H5\"/>",
  "mode": "stroke"
 },
 {
  "name": "gift",
  "category": "commerce",
  "tags": [
   "present"
  ],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"3\" y=\"8\" width=\"18\" height=\"4\" rx=\"1\"/><path d=\"M5 12v9h14v-9M12 8v13M12 8c-1-3-5-4-5-1.5S10 8 12 8zM12 8c1-3 5-4 5-1.5S14 8 12 8z\"/>",
  "mode": "stroke"
 },
 {
  "name": "rocket",
  "category": "commerce",
  "tags": [
   "launch",
   "startup"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"m12 15-3-3c1-5 5-9 11-9 0 6-4 10-9 11z\"/><path d=\"M9 12H5l2.5-4H12M12 15v4l4-2.5V12\"/><circle cx=\"15\" cy=\"9\" r=\"1.5\"/>",
  "mode": "stroke"
 },
 {
  "name": "tag",
  "category": "commerce",
  "tags": [
   "price",
   "label"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M3 12V4a1 1 0 0 1 1-1h8l9 9-9 9z\"/><circle cx=\"8\" cy=\"8\" r=\"1.5\"/>",
  "mode": "stroke"
 },
 {
  "name": "target",
  "category": "commerce",
  "tags": [
   "goal",
   "aim"
  ],
  "viewBox": "0 0 24 24",
  "body": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><circle cx=\"12\" cy=\"12\" r=\"5\"/><circle cx=\"12\" cy=\"12\" r=\"1\"/>",
  "mode": "stroke"
 },
 {
  "name": "truck",
  "category": "commerce",
  "tags": [
   "delivery",
   "shipping"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M2 6h12v10H2zM14 9h4l3 3v4h-7\"/><circle cx=\"6\" cy=\"18\" r=\"2\"/><circle cx=\"17\" cy=\"18\" r=\"2\"/>",
  "mode": "stroke"
 },
 {
  "name": "bell",
  "category": "communication",
  "tags": [
   "notification",
   "alert"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M6 16v-5a6 6 0 0 1 12 0v5l2 2H4z\"/><path d=\"M10 21h4\"/>",
  "mode": "stroke"
 },
 {
  "name": "chat",
  "category": "communication",
  "tags": [
   "message",
   "comment",
   "bubble"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M4 5h16v11H9l-5 4z\"/>",
  "mode": "stroke"
 },
 {
  "name": "globe",
  "category": "communication",
  "tags": [
   "world",
   "web",
   "internet",
   "language"
  ],
  "viewBox": "0 0 24 24",
  "body": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M3 12h18M12 3c3 3.5 3 14.5 0 18M12 3c-3 3.5-3 14.5 0 18\"/>",
  "mode": "stroke"
 },
 {
  "name": "mail",
  "category": "communication",
  "tags": [
   "email",
   "envelope",
   "message"
  ],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"3\" y=\"5\" width=\"18\" height=\"14\" rx=\"2\"/><path d=\"m3 7 9 6 9-6\"/>",
  "mode": "stroke"
 },
 {
  "name": "mic",
  "category": "communication",
  "tags": [
   "microphone",
   "audio",
   "record",
   "voice"
  ],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"9\" y=\"3\" width=\"6\" height=\"11\" rx=\"3\"/><path d=\"M5 11a7 7 0 0 0 14 0M12 18v3\"/>",
  "mode": "stroke"
 },
 {
  "name": "send",
  "category": "communication",
  "tags": [
   "paper plane",
   "submit"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M21 3 10 14M21 3l-7 18-4-7-7-4z\"/>",
  "mode": "stroke"
 },
 {
  "name": "smile",
  "category": "communication",
  "tags": [
   "emoji",
   "happy",
   "face"
  ],
  "viewBox": "0 0 24 24",
  "body": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M8.5 14.5a4.5 4.5 0 0 0 7 0M9 9.5h.01M15 9.5h.01\"/>",
  "mode": "stroke"
 },
 {
  "name": "user",
  "category": "communication",
  "tags": [
   "person",
   "account",
   "profile",
   "avatar"
  ],
  "viewBox": "0 0 24 24",
  "body": "<circle cx=\"12\" cy=\"8\" r=\"4\"/><path d=\"M4 21a8 8 0 0 1 16 0\"/>",
  "mode": "stroke"
 },
 {
  "name": "users",
  "category": "communication",
  "tags": [
   "people",
   "team",
   "group"
  ],
  "viewBox": "0 0 24 24",
  "body": "<circle cx=\"9\" cy=\"8\" r=\"3.5\"/><path d=\"M2.5 20a6.5 6.5 0 0 1 13 0\"/><path d=\"M15.5 4.5a3.5 3.5 0 0 1 0 7\"/><path d=\"M18 14.5a6.5 6.5 0 0 1 3.5 5.5\"/>",
  "mode": "stroke"
 },
 {
  "name": "battery",
  "category": "devices",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"2\" y=\"7\" width=\"17\" height=\"10\" rx=\"2\"/><path d=\"M22 10.5v3M5 10v4M8 10v4\"/>",
  "mode": "stroke"
 },
 {
  "name": "code",
  "category": "devices",
  "tags": [
   "develop",
   "programming"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"m8 7-5 5 5 5M16 7l5 5-5 5M14 4l-4 16\"/>",
  "mode": "stroke"
 },
 {
  "name": "cpu",
  "category": "devices",
  "tags": [
   "chip",
   "processor",
   "hardware"
  ],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"6\" y=\"6\" width=\"12\" height=\"12\" rx=\"1.5\"/><rect x=\"9.5\" y=\"9.5\" width=\"5\" height=\"5\"/><path d=\"M9 2v4M15 2v4M9 18v4M15 18v4M2 9h4M2 15h4M18 9h4M18 15h4\"/>",
  "mode": "stroke"
 },
 {
  "name": "database",
  "category": "devices",
  "tags": [
   "storage",
   "data",
   "db"
  ],
  "viewBox": "0 0 24 24",
  "body": "<ellipse cx=\"12\" cy=\"5.5\" rx=\"7\" ry=\"2.5\"/><path d=\"M5 5.5v13c0 1.4 3.1 2.5 7 2.5s7-1.1 7-2.5v-13M5 12c0 1.4 3.1 2.5 7 2.5s7-1.1 7-2.5\"/>",
  "mode": "stroke"
 },
 {
  "name": "laptop",
  "category": "devices",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"4\" y=\"5\" width=\"16\" height=\"11\" rx=\"1.5\"/><path d=\"M2 19h20\"/>",
  "mode": "stroke"
 },
 {
  "name": "monitor",
  "category": "devices",
  "tags": [
   "desktop",
   "screen",
   "display"
  ],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"2\" y=\"4\" width=\"20\" height=\"13\" rx=\"2\"/><path d=\"M8 21h8M12 17v4\"/>",
  "mode": "stroke"
 },
 {
  "name": "phone",
  "category": "devices",
  "tags": [
   "mobile",
   "smartphone",
   "device"
  ],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"7\" y=\"2\" width=\"10\" height=\"20\" rx=\"2\"/><path d=\"M11 18h2\"/>",
  "mode": "stroke"
 },
 {
  "name": "server",
  "category": "devices",
  "tags": [
   "hosting",
   "rack"
  ],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"3\" y=\"4\" width=\"18\" height=\"7\" rx=\"1.5\"/><rect x=\"3\" y=\"13\" width=\"18\" height=\"7\" rx=\"1.5\"/><path d=\"M7 7.5h.01M7 16.5h.01\"/>",
  "mode": "stroke"
 },
 {
  "name": "terminal",
  "category": "devices",
  "tags": [
   "console",
   "shell",
   "cli"
  ],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"3\" y=\"4\" width=\"18\" height=\"16\" rx=\"2\"/><path d=\"m7 9 3 3-3 3M13 15h4\"/>",
  "mode": "stroke"
 },
 {
  "name": "wifi",
  "category": "devices",
  "tags": [
   "wireless",
   "network",
   "signal"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M2 9a15 15 0 0 1 20 0M5 12.5a10 10 0 0 1 14 0M8.5 16a5 5 0 0 1 7 0M12 19.5h.01\"/>",
  "mode": "stroke"
 },
 {
  "name": "book",
  "category": "files",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M4 4.5A1.5 1.5 0 0 1 5.5 3H20v15H5.5A1.5 1.5 0 0 0 4 19.5z\"/><path d=\"M4 19.5A1.5 1.5 0 0 0 5.5 21H20v-3\"/>",
  "mode": "stroke"
 },
 {
  "name": "calendar",
  "category": "files",
  "tags": [
   "date",
   "schedule",
   "event"
  ],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"3\" y=\"5\" width=\"18\" height=\"16\" rx=\"2\"/><path d=\"M3 10h18M8 3v4M16 3v4\"/>",
  "mode": "stroke"
 },
 {
  "name": "clock",
  "category": "files",
  "tags": [
   "time",
   "history"
  ],
  "viewBox": "0 0 24 24",
  "body": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M12 7v5l3 2\"/>",
  "mode": "stroke"
 },
 {
  "name": "file-text",
  "category": "files",
  "tags": [
   "document",
   "text"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M6 3h8l5 5v13H6z\"/><path d=\"M14 3v5h5M9 13h6M9 17h6\"/>",
  "mode": "stroke"
 },
 {
  "name": "file",
  "category": "files",
  "tags": [
   "document",
   "page"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M6 3h8l5 5v13H6z\"/><path d=\"M14 3v5h5\"/>",
  "mode": "stroke"
 },
 {
  "name": "folder",
  "category": "files",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M3 6a1 1 0 0 1 1-1h5l2 2h9a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z\"/>",
  "mode": "stroke"
 },
 {
  "name": "package",
  "category": "files",
  "tags": [
   "box",
   "shipping",
   "delivery"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M12 3 3 7.5v9L12 21l9-4.5v-9z\"/><path d=\"M3 7.5 12 12l9-4.5M12 12v9\"/>",
  "mode": "stroke"
 },
 {
  "name": "bookmark",
  "category": "interface",
  "tags": [
   "save"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M6 3h12v18l-6-4-6 4z\"/>",
  "mode": "stroke"
 },
 {
  "name": "check",
  "category": "interface",
  "tags": [
   "done",
   "tick",
   "ok",
   "confirm"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"m5 12.5 4.5 4.5L19 7\"/>",
  "mode": "stroke"
 },
 {
  "name": "close",
  "category": "interface",
  "tags": [
   "x",
   "cancel",
   "remove",
   "dismiss"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M6 6l12 12M18 6 6 18\"/>",
  "mode": "stroke"
 },
 {
  "name": "copy",
  "category": "interface",
  "tags": [
   "duplicate",
   "clone"
  ],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"8\" y=\"8\" width=\"12\" height=\"12\" rx=\"2\"/><path d=\"M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2\"/>",
  "mode": "stroke"
 },
 {
  "name": "download",
  "category": "interface",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M12 4v11M7 10l5 5 5-5M4 20h16\"/>",
  "mode": "stroke"
 },
 {
  "name": "edit",
  "category": "interface",
  "tags": [
   "pencil",
   "write",
   "modify"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M4 20h4L19 9l-4-4L4 16z\"/><path d=\"m13 7 4 4\"/>",
  "mode": "stroke"
 },
 {
  "name": "external-link",
  "category": "interface",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M14 4h6v6M20 4l-9 9M18 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h5\"/>",
  "mode": "stroke"
 },
 {
  "name": "eye-off",
  "category": "interface",
  "tags": [
   "hide",
   "hidden",
   "invisible"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12z\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/><path d=\"M3 3l18 18\"/>",
  "mode": "stroke"
 },
 {
  "name": "eye",
  "category": "interface",
  "tags": [
   "view",
   "show",
   "visible"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12z\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/>",
  "mode": "stroke"
 },
 {
  "name": "filter",
  "category": "interface",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M3 5h18l-7 8v6l-4 2v-8z\"/>",
  "mode": "stroke"
 },
 {
  "name": "grid",
  "category": "interface",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"4\" y=\"4\" width=\"7\" height=\"7\" rx=\"1.5\"/><rect x=\"13\" y=\"4\" width=\"7\" height=\"7\" rx=\"1.5\"/><rect x=\"4\" y=\"13\" width=\"7\" height=\"7\" rx=\"1.5\"/><rect x=\"13\" y=\"13\" width=\"7\" height=\"7\" rx=\"1.5\"/>",
  "mode": "stroke"
 },
 {
  "name": "heart",
  "category": "interface",
  "tags": [
   "like",
   "love",
   "favorite"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M12 20s-8-4.6-8-10.5A4.5 4.5 0 0 1 12 7a4.5 4.5 0 0 1 8 2.5C20 15.4 12 20 12 20z\"/>",
  "mode": "stroke"
 },
 {
  "name": "home",
  "category": "interface",
  "tags": [
   "house",
   "start",
   "main"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M3 10.5 12 3l9 7.5\"/><path d=\"M5 9v11h14V9\"/><path d=\"M10 20v-6h4v6\"/>",
  "mode": "stroke"
 },
 {
  "name": "link",
  "category": "interface",
  "tags": [
   "chain",
   "url"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M10 14a4 4 0 0 0 5.7 0l3-3a4 4 0 0 0-5.7-5.7l-1 1\"/><path d=\"M14 10a4 4 0 0 0-5.7 0l-3 3a4 4 0 0 0 5.7 5.7l1-1\"/>",
  "mode": "stroke"
 },
 {
  "name": "list",
  "category": "interface",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M9 6h11M9 12h11M9 18h11\"/><circle cx=\"4.5\" cy=\"6\" r=\"1\"/><circle cx=\"4.5\" cy=\"12\" r=\"1\"/><circle cx=\"4.5\" cy=\"18\" r=\"1\"/>",
  "mode": "stroke"
 },
 {
  "name": "log-out",
  "category": "interface",
  "tags": [
   "sign out",
   "exit"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M9 4H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h4M16 8l4 4-4 4M20 12H9\"/>",
  "mode": "stroke"
 },
 {
  "name": "menu",
  "category": "interface",
  "tags": [
   "hamburger",
   "navigation"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M4 6h16M4 12h16M4 18h16\"/>",
  "mode": "stroke"
 },
 {
  "name": "minus",
  "category": "interface",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M5 12h14\"/>",
  "mode": "stroke"
 },
 {
  "name": "more-horizontal",
  "category": "interface",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<circle cx=\"5\" cy=\"12\" r=\"1\"/><circle cx=\"12\" cy=\"12\" r=\"1\"/><circle cx=\"19\" cy=\"12\" r=\"1\"/>",
  "mode": "stroke"
 },
 {
  "name": "more-vertical",
  "category": "interface",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<circle cx=\"12\" cy=\"5\" r=\"1\"/><circle cx=\"12\" cy=\"12\" r=\"1\"/><circle cx=\"12\" cy=\"19\" r=\"1\"/>",
  "mode": "stroke"
 },
 {
  "name": "plus",
  "category": "interface",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M12 5v14M5 12h14\"/>",
  "mode": "stroke"
 },
 {
  "name": "refresh",
  "category": "interface",
  "tags": [
   "reload",
   "sync"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M20 11a8 8 0 0 0-14.5-4.5L4 8M4 4v4h4M4 13a8 8 0 0 0 14.5 4.5L20 16M20 20v-4h-4\"/>",
  "mode": "stroke"
 },
 {
  "name": "search",
  "category": "interface",
  "tags": [
   "find",
   "magnifier",
   "lookup"
  ],
  "viewBox": "0 0 24 24",
  "body": "<circle cx=\"11\" cy=\"11\" r=\"7\"/><path d=\"m20 20-3.5-3.5\"/>",
  "mode": "stroke"
 },
 {
  "name": "share",
  "category": "interface",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<circle cx=\"6\" cy=\"12\" r=\"2.5\"/><circle cx=\"18\" cy=\"5.5\" r=\"2.5\"/><circle cx=\"18\" cy=\"18.5\" r=\"2.5\"/><path d=\"m8.2 10.8 7.6-4M8.2 13.2l7.6 4\"/>",
  "mode": "stroke"
 },
 {
  "name": "sliders",
  "category": "interface",
  "tags": [
   "settings",
   "controls",
   "adjust",
   "preferences"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M4 6h9M17 6h3M4 12h3M11 12h9M4 18h11M19 18h1\"/><circle cx=\"15\" cy=\"6\" r=\"2\"/><circle cx=\"9\" cy=\"12\" r=\"2\"/><circle cx=\"17\" cy=\"18\" r=\"2\"/>",
  "mode": "stroke"
 },
 {
  "name": "sparkle",
  "category": "interface",
  "tags": [
   "ai",
   "magic",
   "new"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M12 5c.5 4.5 2.5 6.5 7 7-4.5.5-6.5 2.5-7 7-.5-4.5-2.5-6.5-7-7 4.5-.5 6.5-2.5 7-7z\"/>",
  "mode": "stroke"
 },
 {
  "name": "star",
  "category": "interface",
  "tags": [
   "favorite",
   "rating"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"m12 3 2.7 5.6 6.1.9-4.4 4.3 1 6.1L12 17l-5.4 2.9 1-6.1-4.4-4.3 6.1-.9z\"/>",
  "mode": "stroke"
 },
 {
  "name": "toggle",
  "category": "interface",
  "tags": [
   "switch"
  ],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"2\" y=\"6\" width=\"20\" height=\"12\" rx=\"6\"/><circle cx=\"16\" cy=\"12\" r=\"3\"/>",
  "mode": "stroke"
 },
 {
  "name": "trash",
  "category": "interface",
  "tags": [
   "delete",
   "bin",
   "remove"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M4 7h16M10 3h4M6 7l1 14h10l1-14M10 11v6M14 11v6\"/>",
  "mode": "stroke"
 },
 {
  "name": "upload",
  "category": "interface",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M12 15V4M7 9l5-5 5 5M4 20h16\"/>",
  "mode": "stroke"
 },
 {
  "name": "camera",
  "category": "media",
  "tags": [
   "photo"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M3 8a1 1 0 0 1 1-1h3l2-3h6l2 3h3a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z\"/><circle cx=\"12\" cy=\"13\" r=\"3.5\"/>",
  "mode": "stroke"
 },
 {
  "name": "image",
  "category": "media",
  "tags": [
   "picture",
   "photo"
  ],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"3\" y=\"4\" width=\"18\" height=\"16\" rx=\"2\"/><circle cx=\"9\" cy=\"10\" r=\"2\"/><path d=\"m21 16-5-5-9 9\"/>",
  "mode": "stroke"
 },
 {
  "name": "layers",
  "category": "media",
  "tags": [
   "stack"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"m12 3 9 5-9 5-9-5z\"/><path d=\"m3 12.5 9 5 9-5\"/><path d=\"m3 16.5 9 5 9-5\"/>",
  "mode": "stroke"
 },
 {
  "name": "music",
  "category": "media",
  "tags": [
   "song",
   "audio",
   "note"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M9 18V5l11-2v13\"/><circle cx=\"6.5\" cy=\"18\" r=\"2.5\"/><circle cx=\"17.5\" cy=\"16\" r=\"2.5\"/>",
  "mode": "stroke"
 },
 {
  "name": "pause",
  "category": "media",
  "tags": [
   "stop"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M8 5v14M16 5v14\"/>",
  "mode": "stroke"
 },
 {
  "name": "play",
  "category": "media",
  "tags": [
   "start",
   "video"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M7 4v16l13-8z\"/>",
  "mode": "stroke"
 },
 {
  "name": "volume",
  "category": "media",
  "tags": [
   "sound",
   "speaker",
   "audio"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M4 9h4l5-4v14l-5-4H4z\"/><path d=\"M16.5 8.5a5 5 0 0 1 0 7M19 6a8.5 8.5 0 0 1 0 12\"/>",
  "mode": "stroke"
 },
 {
  "name": "bolt",
  "category": "nature",
  "tags": [
   "lightning",
   "flash",
   "power",
   "energy"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M13 2 4 14h7l-1 8 9-12h-7z\"/>",
  "mode": "stroke"
 },
 {
  "name": "cloud",
  "category": "nature",
  "tags": [
   "weather",
   "storage"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M7 18a4 4 0 0 1-.5-8 5.5 5.5 0 0 1 10.6-1.5A4.5 4.5 0 0 1 17.5 18z\"/>",
  "mode": "stroke"
 },
 {
  "name": "coffee",
  "category": "nature",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M4 9h13v5a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5z\"/><path d=\"M17 11h1.5a2.5 2.5 0 0 1 0 5H17M8 3v3M12 3v3\"/>",
  "mode": "stroke"
 },
 {
  "name": "compass",
  "category": "nature",
  "tags": [
   "explore",
   "navigation"
  ],
  "viewBox": "0 0 24 24",
  "body": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"m15.5 8.5-2 5-5 2 2-5z\"/>",
  "mode": "stroke"
 },
 {
  "name": "droplet",
  "category": "nature",
  "tags": [
   "water",
   "drop"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M12 3s6 6.5 6 11a6 6 0 0 1-12 0c0-4.5 6-11 6-11z\"/>",
  "mode": "stroke"
 },
 {
  "name": "leaf",
  "category": "nature",
  "tags": [
   "eco",
   "nature",
   "plant"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M5 19C5 10 10 5 20 4c0 10-5 15-14 15z\"/><path d=\"m5 19 8-8\"/>",
  "mode": "stroke"
 },
 {
  "name": "map-pin",
  "category": "nature",
  "tags": [
   "location",
   "place",
   "marker"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M12 21s-7-6-7-11a7 7 0 0 1 14 0c0 5-7 11-7 11z\"/><circle cx=\"12\" cy=\"10\" r=\"2.5\"/>",
  "mode": "stroke"
 },
 {
  "name": "moon",
  "category": "nature",
  "tags": [
   "dark",
   "night"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M20 14.5A8 8 0 1 1 9.5 4a6.5 6.5 0 0 0 10.5 10.5z\"/>",
  "mode": "stroke"
 },
 {
  "name": "sun",
  "category": "nature",
  "tags": [
   "light",
   "day",
   "weather"
  ],
  "viewBox": "0 0 24 24",
  "body": "<circle cx=\"12\" cy=\"12\" r=\"4\"/><path d=\"M12 2v2M12 20v2M2 12h2M20 12h2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4\"/>",
  "mode": "stroke"
 },
 {
  "name": "alert-triangle",
  "category": "security",
  "tags": [
   "warning",
   "danger",
   "error"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M12 3 2 20h20z\"/><path d=\"M12 10v4M12 17h.01\"/>",
  "mode": "stroke"
 },
 {
  "name": "check-circle",
  "category": "security",
  "tags": [
   "success",
   "done"
  ],
  "viewBox": "0 0 24 24",
  "body": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"m8 12 3 3 5-6\"/>",
  "mode": "stroke"
 },
 {
  "name": "help-circle",
  "category": "security",
  "tags": [
   "question",
   "support"
  ],
  "viewBox": "0 0 24 24",
  "body": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.6.3-1 .9-1 1.5v.7M12 17h.01\"/>",
  "mode": "stroke"
 },
 {
  "name": "info",
  "category": "security",
  "tags": [
   "information",
   "about"
  ],
  "viewBox": "0 0 24 24",
  "body": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M12 11v5M12 8h.01\"/>",
  "mode": "stroke"
 },
 {
  "name": "key",
  "category": "security",
  "tags": [
   "password",
   "access"
  ],
  "viewBox": "0 0 24 24",
  "body": "<circle cx=\"8\" cy=\"15\" r=\"4\"/><path d=\"m11 12 9-9M17 6l3 3M15 8l2 2\"/>",
  "mode": "stroke"
 },
 {
  "name": "lock",
  "category": "security",
  "tags": [
   "secure",
   "password",
   "private"
  ],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"4\" y=\"10\" width=\"16\" height=\"11\" rx=\"2\"/><path d=\"M8 10V7a4 4 0 0 1 8 0v3\"/>",
  "mode": "stroke"
 },
 {
  "name": "shield-check",
  "category": "security",
  "tags": [],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M12 3 4 6v6c0 5 3.5 8 8 9 4.5-1 8-4 8-9V6z\"/><path d=\"m9 12 2 2 4-4\"/>",
  "mode": "stroke"
 },
 {
  "name": "shield",
  "category": "security",
  "tags": [
   "security",
   "protect"
  ],
  "viewBox": "0 0 24 24",
  "body": "<path d=\"M12 3 4 6v6c0 5 3.5 8 8 9 4.5-1 8-4 8-9V6z\"/>",
  "mode": "stroke"
 },
 {
  "name": "unlock",
  "category": "security",
  "tags": [
   "open"
  ],
  "viewBox": "0 0 24 24",
  "body": "<rect x=\"4\" y=\"10\" width=\"16\" height=\"11\" rx=\"2\"/><path d=\"M8 10V7a4 4 0 0 1 7.5-2\"/>",
  "mode": "stroke"
 },
 {
  "name": "x-circle",
  "category": "security",
  "tags": [
   "error",
   "fail",
   "cancel"
  ],
  "viewBox": "0 0 24 24",
  "body": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"m9 9 6 6M15 9l-6 6\"/>",
  "mode": "stroke"
 }
];
