// Reads every SVG in icons/<category>/<name>.svg and writes:
//   icons.js        – data the website loads (works straight from file://)
//   dist/sprite.svg – a <symbol> sprite you can drop into any project
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync, statSync } from "node:fs";
import { join, basename } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const ICON_DIR = join(ROOT, "icons");
const tags = existsSync(join(ICON_DIR, "tags.json"))
  ? JSON.parse(readFileSync(join(ICON_DIR, "tags.json"), "utf8"))
  : {};

const clean = (s) =>
  s
    .replace(/<\?xml[\s\S]*?\?>/g, "")
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/\son\w+\s*=\s*("[^"]*"|'[^']*')/gi, "")
    .replace(/\s+/g, " ")
    .trim();

function parse(file) {
  const src = clean(readFileSync(file, "utf8"));
  const open = src.match(/<svg\b([^>]*)>/i);
  if (!open) throw new Error(`${file}: no <svg> tag`);
  const attrs = open[1];
  const attr = (n) => (attrs.match(new RegExp(`\\s${n}\\s*=\\s*["']([^"']*)["']`, "i")) || [])[1];
  const w = attr("width"), h = attr("height");
  const viewBox = attr("viewBox") || (w && h ? `0 0 ${parseFloat(w)} ${parseFloat(h)}` : "0 0 24 24");
  const body = src.slice(open.index + open[0].length, src.lastIndexOf("</svg>")).trim();
  // Outline icons let the site control stroke width; filled icons only get colour.
  const mode = attr("fill") === "none" || (attr("stroke") && attr("stroke") !== "none") ? "stroke" : "fill";
  return { viewBox, body, mode };
}

const icons = [];
for (const category of readdirSync(ICON_DIR).sort()) {
  const dir = join(ICON_DIR, category);
  if (!statSync(dir).isDirectory()) continue;
  for (const f of readdirSync(dir).filter((f) => f.endsWith(".svg")).sort()) {
    const name = basename(f, ".svg");
    icons.push({ name, category, tags: tags[name] || [], ...parse(join(dir, f)) });
  }
}

writeFileSync(
  join(ROOT, "icons.js"),
  `// Generated by scripts/build.mjs – do not edit. Run \`npm run build\` after adding icons.\nwindow.ICONS = ${JSON.stringify(icons, null, 1)};\n`
);

mkdirSync(join(ROOT, "dist"), { recursive: true });
const symbols = icons.map((i) => {
  const paint = i.mode === "stroke"
    ? ' fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"'
    : ' fill="currentColor"';
  return `  <symbol id="${i.name}" viewBox="${i.viewBox}"${paint}>${i.body}</symbol>`;
});
writeFileSync(
  join(ROOT, "dist", "sprite.svg"),
  `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n${symbols.join("\n")}\n</svg>\n`
);

const dupes = icons.map((i) => i.name).filter((n, i, a) => a.indexOf(n) !== i);
if (dupes.length) console.warn(`Warning: duplicate icon names: ${[...new Set(dupes)].join(", ")}`);
console.log(`Built ${icons.length} icons in ${new Set(icons.map((i) => i.category)).size} categories.`);
